# Generated by Django 3.2.3 on 2021-05-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='image.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
