# Generated by Django 3.2.3 on 2021-05-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_auto_20210518_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('mot', models.CharField(max_length=400)),
                ('montant', models.IntegerField()),
                ('totalite', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.article')),
            ],
        ),
    ]
