# Generated by Django 3.2.3 on 2021-05-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_cadeau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cadeau',
            name='mot',
            field=models.TextField(),
        ),
    ]
