# Generated by Django 3.2.3 on 2021-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_auto_20210704_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(default='Autre', max_length=100),
        ),
    ]
