# Generated by Django 3.2.3 on 2021-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_alter_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='default_cadeau.jpg', upload_to='images/'),
        ),
    ]
