# Generated by Django 3.2.3 on 2021-07-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_article_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
